### ISSUE TITLE
WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by moonEEVEEXwX** [opZywl/EZ4H#10]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/D:/EZ4H/EZ4H-B20210125.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

提示出这个
然后java就链接不上了（但是没有 --illegal-access=warn 这个吖）
XwX

**Comment by hax0r31337** [comment]
话说大佬有没有完整的日志QAQ
我想看看到底在哪报错的

**Comment by moonEEVEEXwX** [comment]
> 话说大佬有没有完整的日志QAQ
> 我想看看到底在哪报错的

WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
[36m08:49:35[m [[34mINFO [m] Init Protocol...
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/D:/EZ4H/EZ4H-B20210125.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
开debug只有这个qwq

**Comment by moonEEVEEXwX** [comment]
> 话说大佬有没有完整的日志QAQ
> 我想看看到底在哪报错的


D:\EZ4H>java -Xms512M -jar EZ4H-B20210125.jar
[36m08:49:34[m [[34mINFO [m] Loading EZ4H vB20210125
[36m08:49:34[m [[34mINFO [m] Init files...
[36m08:49:35[m [[31mWARN [m] Debug Mode Enabled in Config
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
[36m08:49:35[m [[34mINFO [m] Init Protocol...
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/D:/EZ4H/EZ4H-B20210125.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[36m08:49:39[m [[34mINFO [m] Loading things...
[36m08:49:39[m [[34mINFO [m] Done!(6667 ms)
java.net.ConnectException: Connection timed out: connect
        at java.base/java.net.PlainSocketImpl.connect0(Native Method)
        at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
        at java.base/java.net.Socket.connect(Socket.java:608)
        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:285)
        at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1367)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1342)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:246)
        at me.liuli.ez4h.utils.MetricsLite.sendData(MetricsLite.java:174)
        at me.liuli.ez4h.utils.MetricsLite.lambda$submitData$0(MetricsLite.java:144)
        at java.base/java.lang.Thread.run(Thread.java:834)
总共有这样的qwq

**Comment by hax0r31337** [comment]
啊这？
第二个报错是bstat信息上传不上去(idk why)
还有你的版本好旧，等v0.3好了你再试试新的？

**Comment by hax0r31337** [comment]
fixed
