### ISSUE TITLE
BDS support?

### ISSUE THREAD

**Issue by ghost** [opZywl/EZ4H#6]
java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException
        at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
        at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
        at java.util.concurrent.CompletableFuture.uniApply(Unknown Source)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
        at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
        at com.nukkitx.network.raknet.RakNetClient.onTick(RakNetClient.java:114)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:131)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.util.concurrent.TimeoutException
        ... 8 more

**Comment by hax0r31337** [comment]
Timeout?idk why you timeout...
but it dont support BDS
when i try to connect a BDS server,i got kicked as soon as i received the StartGamePacket
reason is "disconnectScreen.unexpectedPacket"
maybe i send a badpacket to server.i'll fix it

**Comment by hax0r31337** [comment]
下次更新支持bds
不过玩家移动有点问题，打人挖方块之类的没问题
