### ISSUE TITLE
无法运行在中文目录

### ISSUE THREAD

**Issue by ghost** [opZywl/EZ4H#7]
java.io.FileNotFoundException: C:\Users\seaic\Desktop\%e9%a1%b9%e7%9b%ae\be%e6%9c%8d\EZ4H\EZ4H.jar (系统找不到指定的路径。)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.jar.JarFile.<init>(Unknown Source)
        at java.util.jar.JarFile.<init>(Unknown Source)
        at me.liuli.ez4h.utils.FileUtils.readJarText(FileUtils.java:71)
        at me.liuli.ez4h.translators.bedrock.entity.MobEffectPacketTranslator.<init>(MobEffectPacketTranslator.java:20)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at java.lang.Class.newInstance(Unknown Source)
        at me.liuli.ez4h.EZ4H.initProtocol(EZ4H.java:85)
        at me.liuli.ez4h.EZ4H.main(EZ4H.java:55)
        at me.liuli.ez4h.Initialization.main(Initialization.java:18)
java.lang.NullPointerException
        at me.liuli.ez4h.translators.bedrock.entity.MobEffectPacketTranslator.<init>(MobEffectPacketTranslator.java:21)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at java.lang.Class.newInstance(Unknown Source)
        at me.liuli.ez4h.EZ4H.initProtocol(EZ4H.java:85)
        at me.liuli.ez4h.EZ4H.main(EZ4H.java:55)
        at me.liuli.ez4h.Initialization.main(Initialization.java:18)
java.io.FileNotFoundException: C:\Users\seaic\Desktop\%e9%a1%b9%e7%9b%ae\be%e6%9c%8d\EZ4H\EZ4H.jar (系统找不到指定的路径。)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.jar.JarFile.<init>(Unknown Source)
        at java.util.jar.JarFile.<init>(Unknown Source)
        at me.liuli.ez4h.utils.FileUtils.readJarText(FileUtils.java:71)
        at me.liuli.ez4h.translators.bedrock.entity.AddEntityPacketTranslator.<init>(AddEntityPacketTranslator.java:32)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at java.lang.Class.newInstance(Unknown Source)
        at me.liuli.ez4h.EZ4H.initProtocol(EZ4H.java:85)
        at me.liuli.ez4h.EZ4H.main(EZ4H.java:55)
        at me.liuli.ez4h.Initialization.main(Initialization.java:18)
java.io.FileNotFoundException: C:\Users\seaic\Desktop\%e9%a1%b9%e7%9b%ae\be%e6%9c%8d\EZ4H\EZ4H.jar (系统找不到指定的路径。)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.jar.JarFile.<init>(Unknown Source)
        at java.util.jar.JarFile.<init>(Unknown Source)
        at me.liuli.ez4h.utils.FileUtils.readJarText(FileUtils.java:71)
        at me.liuli.ez4h.managers.ConverterManager.<init>(ConverterManager.java:24)
        at me.liuli.ez4h.EZ4H.initProtocol(EZ4H.java:106)
        at me.liuli.ez4h.EZ4H.main(EZ4H.java:55)
        at me.liuli.ez4h.Initialization.main(Initialization.java:18)
java.io.FileNotFoundException: C:\Users\seaic\Desktop\%e9%a1%b9%e7%9b%ae\be%e6%9c%8d\EZ4H\EZ4H.jar (系统找不到指定的路径。)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.jar.JarFile.<init>(Unknown Source)
        at java.util.jar.JarFile.<init>(Unknown Source)
        at me.liuli.ez4h.utils.FileUtils.readJarText(FileUtils.java:71)
        at me.liuli.ez4h.managers.ConverterManager.<init>(ConverterManager.java:24)
        at me.liuli.ez4h.EZ4H.initProtocol(EZ4H.java:106)
        at me.liuli.ez4h.EZ4H.main(EZ4H.java:55)
        at me.liuli.ez4h.Initialization.main(Initialization.java:18)
Exception in thread "main" java.lang.NullPointerException
        at me.liuli.ez4h.translators.converters.BlockConverter.<init>(BlockConverter.java:23)
        at me.liuli.ez4h.managers.ConverterManager.<init>(ConverterManager.java:24)
        at me.liuli.ez4h.EZ4H.initProtocol(EZ4H.java:106)
        at me.liuli.ez4h.EZ4H.main(EZ4H.java:55)
        at me.liuli.ez4h.Initialization.main(Initialization.java:18)

**Comment by hax0r31337** [comment]
这。。。我不知道怎么修了
我试试修吧

**Comment by ghost** [comment]
应该因为是中文被转成了url

**Comment by hax0r31337** [comment]
bug fixed
